# Test data.

licenses(["notice"])

package(
    # unused internal package attribute
    default_hdrs_check = "strict",
    default_visibility = ["//saxml:internal"],
)

filegroup(
    name = "test_data",
    srcs = glob(["**"]),
)
